import { Palette, Pointer, Ruler, Compass, Clock } from "lucide-react";

export const sensorBlocks = [
  {
    type: "sensor_is_color",
    message0: "é cor %1",
    args0: [{ type: "input_value", name: "COLOR" }],
    output: "Boolean",
    colour: "#00BCD4",
    icon: { Icon: Palette, bg: "#00BCD4", alt: "Sensor Cor" },
  },
  {
    type: "sensor_color",
    message0: "cor",
    output: "String",
    colour: "#00BCD4",
    icon: { Icon: Palette, bg: "#00BCD4", alt: "Sensor Cor" },
  },
  {
    type: "sensor_is_reflection_less_than",
    message0: "reflexão < %1",
    args0: [{ type: "input_value", name: "VALUE", check: "Number" }],
    output: "Boolean",
    colour: "#00BCD4",
    icon: { Icon: Palette, bg: "#00BCD4", alt: "Sensor Reflexão" },
  },
  {
    type: "sensor_reflected_light",
    message0: "luz refletida",
    output: "Number",
    colour: "#00BCD4",
    icon: { Icon: Palette, bg: "#00BCD4", alt: "Luz Refletida" },
  },
  {
    type: "sensor_is_pressed",
    message0: "está pressionado",
    output: "Boolean",
    colour: "#00BCD4",
    icon: { Icon: Pointer, bg: "#00BCD4", alt: "Sensor Pressionado" },
  },
  {
    type: "sensor_pressure_percent",
    message0: "pressão %1",
    args0: [{ type: "input_value", name: "VALUE" }],
    output: "Number",
    colour: "#00BCD4",
    icon: { Icon: Pointer, bg: "#00BCD4", alt: "Sensor Pressionado" },
  },
  {
    type: "sensor_is_closer_than",
    message0: "está mais próximo que %1",
    args0: [{ type: "input_value", name: "VALUE" }],
    output: "Boolean",
    colour: "#00BCD4",
    icon: { Icon: Ruler, bg: "#00BCD4", alt: "Sensor Distância" },
  },
  {
    type: "sensor_distance_percent",
    message0: "distância %1",
    args0: [{ type: "input_value", name: "VALUE" }],
    output: "Number",
    colour: "#00BCD4",
    icon: { Icon: Ruler, bg: "#00BCD4", alt: "Sensor Distância" },
  },
  {
    type: "sensor_is_tilted",
    message0: "está inclinado",
    output: "Boolean",
    colour: "#00BCD4",
    icon: { Icon: Compass, bg: "#00BCD4", alt: "Sensor Movimento" },
  },
  {
    type: "sensor_orientation",
    message0: "orientação",
    output: "String",
    colour: "#00BCD4",
    icon: { Icon: Compass, bg: "#00BCD4", alt: "Sensor Orientação" },
  },
  {
    type: "sensor_is_shaken",
    message0: "está sacudido",
    output: "Boolean",
    colour: "#00BCD4",
    icon: { Icon: Compass, bg: "#00BCD4", alt: "Sensor Sacudido" },
  },
  {
    type: "sensor_pitch_angle",
    message0: "ângulo de inclinação",
    output: "Number",
    colour: "#00BCD4",
    icon: { Icon: Compass, bg: "#00BCD4", alt: "Sensor Pitch" },
  },
  {
    type: "sensor_set_yaw_angle_to_zero",
    message0: "definir ângulo yaw para zero",
    previousStatement: null,
    nextStatement: null,
    colour: "#00BCD4",
    icon: { Icon: Compass, bg: "#00BCD4", alt: "Sensor Yaw" },
  },
  {
    type: "sensor_is_button_pressed",
    message0: "botão está pressionado",
    output: "Boolean",
    colour: "#00BCD4",
    icon: { Icon: Pointer, bg: "#00BCD4", alt: "Sensor Pressionado" },
  },
  {
    type: "sensor_timer",
    message0: "temporizador",
    output: "Number",
    colour: "#00BCD4",
    icon: { Icon: Clock, bg: "#00BCD4", alt: "Sensor Temporizador" },
  },
  {
    type: "sensor_reset_timer",
    message0: "resetar temporizador",
    previousStatement: null,
    nextStatement: null,
    colour: "#00BCD4",
    icon: { Icon: Clock, bg: "#00BCD4", alt: "Sensor Temporizador" },
  },
];
