import { Zap, Palette, Pointer, Ruler, Compass, Clock } from "lucide-react";

export const eventBlocks = [
  {
    type: "event_when_program_starts",
    message0: "Quando o programa iniciar",
    nextStatement: null,
    colour: "#FFC107",
    icon: { Icon: Zap, bg: "#FFC107", alt: "Evento" },
  },
  {
    type: "event_when_color",
    message0: "Quando cor %1",
    args0: [{ type: "input_value", name: "COLOR" }],
    nextStatement: null,
    colour: "#FFC107",
    icon: { Icon: Palette, bg: "#FFC107", alt: "Evento" },
  },
  {
    type: "event_when_pressed",
    message0: "Quando pressionado",
    nextStatement: null,
    colour: "#FFC107",
    icon: { Icon: Pointer, bg: "#FFC107", alt: "Evento" },
  },
  {
    type: "event_when_distance",
    message0: "Quando distância %1",
    args0: [{ type: "input_value", name: "VALUE" }],
    nextStatement: null,
    colour: "#FFC107",
    icon: { Icon: Ruler, bg: "#FFC107", alt: "Evento" },
  },
  {
    type: "event_when_tilted",
    message0: "Quando inclinado",
    nextStatement: null,
    colour: "#FFC107",
    icon: { Icon: Compass, bg: "#FFC107", alt: "Evento" },
  },
  {
    type: "event_when_orientation",
    message0: "Quando orientação %1",
    args0: [{ type: "input_value", name: "ORIENTATION" }],
    nextStatement: null,
    colour: "#FFC107",
    icon: { Icon: Compass, bg: "#FFC107", alt: "Evento" },
  },
  {
    type: "event_when_shaken",
    message0: "Quando sacudido",
    nextStatement: null,
    colour: "#FFC107",
    icon: { Icon: Compass, bg: "#FFC107", alt: "Evento" },
  },
  {
    type: "event_when_button_pressed",
    message0: "Quando botão %1 pressionado",
    args0: [{ type: "input_value", name: "BUTTON" }],
    nextStatement: null,
    colour: "#FFC107",
    icon: { Icon: Pointer, bg: "#FFC107", alt: "Evento" },
  },
  {
    type: "event_when_timer_greater_than",
    message0: "Quando temporizador > %1",
    args0: [{ type: "input_value", name: "TIME" }],
    nextStatement: null,
    colour: "#FFC107",
    icon: { Icon: Clock, bg: "#FFC107", alt: "Evento" },
  },
  {
    type: "event_when_condition",
    message0: "Quando condição %1",
    args0: [{ type: "input_value", name: "COND" }],
    nextStatement: null,
    colour: "#FFC107",
    icon: { Icon: Zap, bg: "#FFC107", alt: "Evento" },
  },
];
