import { Palette } from "lucide-react";
import { opSvgDataUrl } from ".";

export const operatorBlocks = [
  {
    type: "math_random_int",
    message0: "Aleatório de %1 até %2",
    args0: [
      { type: "field_input", name: "FROM" },
      { type: "field_input", name: "TO" },
    ],
    output: "Number",
    colour: "#4CAF50",
  },
  {
    type: "logic_equals",
    message0: "%1 %2 %3",
    args0: [
      { type: "field_input", name: "A" },
      {
        type: "field_image",
        src: opSvgDataUrl("=", 44),
        width: 32,
        height: 32,
        alt: "=",
      },
      { type: "field_input", name: "B" },
    ],
    inputsInline: true,
    output: "Boolean",
    colour: "#4CAF50",
  },
  {
    type: "logic_not_equals",
    message0: "%1 %2 %3",
    args0: [
      { type: "field_input", name: "A" },
      {
        type: "field_image",
        src: opSvgDataUrl("≠", 44),
        width: 32,
        height: 32,
        alt: "≠",
      },
      { type: "field_input", name: "B" },
    ],
    inputsInline: true,
    output: "Boolean",
    colour: "#4CAF50",
  },
  {
    type: "logic_lt",
    message0: "%1 %2 %3",
    args0: [
      { type: "field_input", name: "A" },
      {
        type: "field_image",
        src: opSvgDataUrl("<", 44),
        width: 32,
        height: 32,
        alt: "<",
      },
      { type: "field_input", name: "B" },
    ],
    inputsInline: true,
    output: "Boolean",
    colour: "#4CAF50",
  },
  {
    type: "logic_lte",
    message0: "%1 %2 %3",
    args0: [
      { type: "field_input", name: "A" },
      {
        type: "field_image",
        src: opSvgDataUrl("≤", 44),
        width: 32,
        height: 32,
        alt: "≤",
      },
      { type: "field_input", name: "B" },
    ],
    inputsInline: true,
    output: "Boolean",
    colour: "#4CAF50",
  },
  {
    type: "logic_gt",
    message0: "%1 %2 %3",
    args0: [
      { type: "field_input", name: "A" },
      {
        type: "field_image",
        src: opSvgDataUrl(">", 44),
        width: 32,
        height: 32,
        alt: ">",
      },
      { type: "field_input", name: "B" },
    ],
    inputsInline: true,
    output: "Boolean",
    colour: "#4CAF50",
  },
  {
    type: "logic_gte",
    message0: "%1 %2 %3",
    args0: [
      { type: "field_input", name: "A" },
      {
        type: "field_image",
        src: opSvgDataUrl("≥", 44),
        width: 32,
        height: 32,
        alt: "≥",
      },
      { type: "field_input", name: "B" },
    ],
    inputsInline: true,
    output: "Boolean",
    colour: "#4CAF50",
  },
  {
    type: "logic_and",
    message0: "%1 e %2",
    args0: [
      { type: "input_value", name: "A", check: "Boolean" },
      { type: "input_value", name: "B", check: "Boolean" },
    ],
    inputsInline: true,
    output: "Boolean",
    colour: "#4CAF50",
  },
  {
    type: "logic_or",
    message0: "%1 ou %2",
    args0: [
      { type: "input_value", name: "A", check: "Boolean" },
      { type: "input_value", name: "B", check: "Boolean" },
    ],
    inputsInline: true,
    output: "Boolean",
    colour: "#4CAF50",
  },
  {
    type: "logic_negate",
    message0: "é falso que %1",
    args0: [{ type: "input_value", name: "BOOL", check: "Boolean" }],
    output: "Boolean",
    colour: "#4CAF50",
  },
  {
    type: "operator_is_between",
    message0: "%1 entre %2 e %3",
    args0: [
      { type: "field_input", name: "VALUE" },
      { type: "field_input", name: "LOW" },
      { type: "field_input", name: "HIGH" },
    ],
    inputsInline: true,
    output: "Boolean",
    colour: "#4CAF50",
  },
  {
    type: "text_join",
    message0: "juntar %1 e %2",
    args0: [
      { type: "input_value", name: "A" },
      { type: "input_value", name: "B" },
    ],
    output: "String",
    colour: "#4CAF50",
    icon: { Icon: Palette, bg: "#4CAF50", alt: "Texto" },
  },
  {
    type: "text_charAt",
    message0: "caractere em %1 de %2",
    args0: [
      { type: "input_value", name: "AT" },
      { type: "input_value", name: "VALUE" },
    ],
    output: "String",
    colour: "#4CAF50",
    icon: { Icon: Palette, bg: "#4CAF50", alt: "Texto" },
  },
  {
    type: "text_length",
    message0: "tamanho de %1",
    args0: [{ type: "input_value", name: "VALUE" }],
    output: "Number",
    colour: "#4CAF50",
    icon: { Icon: Palette, bg: "#4CAF50", alt: "Texto" },
  },
  {
    type: "text_contains",
    message0: "%1 contém %2",
    args0: [
      { type: "input_value", name: "VALUE" },
      { type: "input_value", name: "SUB" },
    ],
    output: "Boolean",
    colour: "#4CAF50",
    icon: { Icon: Palette, bg: "#4CAF50", alt: "Texto" },
  },
  {
    type: "math_modulo",
    message0: "%1 mod %2",
    args0: [
      { type: "input_value", name: "A" },
      { type: "input_value", name: "B" },
    ],
    output: "Number",
    colour: "#4CAF50",
  },
  {
    type: "math_round",
    message0: "arredondar %1",
    args0: [{ type: "input_value", name: "NUM" }],
    output: "Number",
    colour: "#4CAF50",
  },
  {
    type: "math_single",
    message0: "%1 de %2",
    args0: [
      {
        type: "field_dropdown",
        name: "OP",
        options: [
          ["negativo", "NEG"],
          ["raiz", "ROOT"],
        ],
      },
      { type: "input_value", name: "NUM" },
    ],
    output: "Number",
    colour: "#4CAF50",
  },
];
