export const toolbox = {
  kind: "categoryToolbox",
  contents: [
    // {
    //   kind: "category",
    //   name: "Motores",
    //   cssConfig: {
    //     icon: "toolbox-icon-motores",
    //   },
    //   colour: "#4A90E2",
    //   contents: [
    //     { kind: "block", type: "motor_run_for_duration" },
    //     { kind: "block", type: "motor_go_shortest_path" },
    //     { kind: "block", type: "motor_start" },
    //     { kind: "block", type: "motor_stop" },
    //     { kind: "block", type: "motor_set_speed" },
    //     { kind: "block", type: "motor_position" },
    //     { kind: "block", type: "motor_velocity" },
    //   ],
    // },
    {
      kind: "category",
      name: "Som",
      colour: "#673AB7",
      contents: [
        { kind: "block", type: "sound_play_and_wait" },
        { kind: "block", type: "sound_stop_all" },
        { kind: "block", type: "sound_change_volume_by" },
        { kind: "block", type: "sound_set_volume_to" },
        { kind: "block", type: "sound_volume" },
      ],
    },
    {
      kind: "category",
      name: "Eventos",
      colour: "#FFC107",
      contents: [
        { kind: "block", type: "event_when_program_starts" },
        // { kind: "block", type: "event_when_color" },
        // { kind: "block", type: "event_when_pressed" },
        // { kind: "block", type: "event_when_distance" },
        // { kind: "block", type: "event_when_tilted" },
        // { kind: "block", type: "event_when_orientation" },
        // { kind: "block", type: "event_when_shaken" },
        // { kind: "block", type: "event_when_button_pressed" },
        { kind: "block", type: "event_when_timer_greater_than" },
        // { kind: "block", type: "event_when_condition" },
      ],
    },
    {
      kind: "category",
      name: "Controle",
      colour: "#FF9800",
      contents: [
        { kind: "block", type: "control_wait" },
        { kind: "block", type: "controls_repeat_ext" },
        { kind: "block", type: "control_forever" },
        { kind: "block", type: "controls_if" },
        { kind: "block", type: "controls_if_else" },
        { kind: "block", type: "control_wait_until" },
        { kind: "block", type: "controls_whileUntil" },
        { kind: "block", type: "control_stop_other_scripts" },
        { kind: "block", type: "control_stop" },
      ],
    },
    // {
    //   kind: "category",
    //   name: "Sensores",
    //   colour: "#00BCD4",
    //   contents: [
    //     { kind: "label", text: "Cor" },
    //     { kind: "block", type: "sensor_is_color" },
    //     { kind: "block", type: "sensor_color" },
    //     { kind: "block", type: "sensor_is_reflection_less_than" },
    //     { kind: "block", type: "sensor_reflected_light" },

    //     { kind: "label", text: "Pressão / Botão" },
    //     { kind: "block", type: "sensor_is_pressed" },
    //     { kind: "block", type: "sensor_pressure_percent" },
    //     { kind: "block", type: "sensor_is_button_pressed" },

    //     { kind: "label", text: "Distância" },
    //     { kind: "block", type: "sensor_is_closer_than" },
    //     { kind: "block", type: "sensor_distance_percent" },

    //     { kind: "label", text: "Movimento / Orientação" },
    //     { kind: "block", type: "sensor_is_tilted" },
    //     { kind: "block", type: "sensor_orientation" },
    //     { kind: "block", type: "sensor_is_shaken" },
    //     { kind: "block", type: "sensor_pitch_angle" },
    //     { kind: "block", type: "sensor_set_yaw_angle_to_zero" },

    //     { kind: "label", text: "Timers / Outros" },
    //     { kind: "block", type: "sensor_timer" },
    //     { kind: "block", type: "sensor_reset_timer" },
    //   ],
    // },
    {
      kind: "category",
      name: "Operadores",
      colour: "#4CAF50",
      contents: [
        { kind: "block", type: "math_random_int" },
        { kind: "label", text: "" },
        { kind: "block", type: "math_add" },
        { kind: "block", type: "math_subtract" },
        { kind: "block", type: "math_multiply" },
        { kind: "block", type: "math_divide" },
        { kind: "label", text: "" },
        { kind: "block", type: "logic_equals" },
        { kind: "block", type: "logic_not_equals" },
        { kind: "block", type: "logic_lt" },
        { kind: "block", type: "logic_lte" },
        { kind: "block", type: "logic_gt" },
        { kind: "block", type: "logic_gte" },
        { kind: "label", text: "" },
        { kind: "block", type: "logic_and" },
        { kind: "block", type: "logic_or" },
        { kind: "block", type: "logic_negate" },
        { kind: "block", type: "operator_is_between" },
      ],
    },
    {
      kind: "category",
      name: "Variáveis",
      colour: "#FF5722",
      custom: "VARIABLE",
    },
    {
      kind: "category",
      name: "Meus Blocos",
      colour: "#F44336",
      custom: "PROCEDURE",
    },
  ],
};
