name: Build & Release Pi Zero 2W executable

permissions:
  contents: write

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image (gera executável dentro do container)
        run: |
          docker buildx build \
            --platform linux/arm/v7 \
            --file .github/docker/pi-build/Dockerfile \
            --tag hub-pi-build:latest \
            --cache-from=type=gha \
            --cache-to=type=gha,mode=max \
            --load \
            .

      - name: Save Docker image como artifact
        run: docker save hub-pi-build:latest | gzip > hub-pi-build.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: hub-pi-build-image
          path: hub-pi-build.tar.gz

  package:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: hub-pi-build-image

      - name: Load Docker image
        run: docker load < hub-pi-build.tar.gz

      - name: Extract executable from image
        run: |
          mkdir -p dist
          docker create --name extract hub-pi-build:latest
          docker cp extract:/src/dist/hub-pi-zero-2w ./dist/
          docker rm extract

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hub-pi-zero-2w
          path: dist/hub-pi-zero-2w*

  release:
    runs-on: ubuntu-latest
    needs: package
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download executable
        uses: actions/download-artifact@v4
        with:
          name: hub-pi-zero-2w
          path: dist

      - name: Create GitHub Release and upload asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/hub-pi-zero-2w*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
